-- =====================================================
-- IMPORT DATA TO CLINIC SYSTEM
-- =====================================================

USE clinic_system;

SET FOREIGN_KEY_CHECKS = 0;

-- Xóa dữ liệu cũ (nếu muốn)
TRUNCATE TABLE service;
TRUNCATE TABLE staff;
TRUNCATE TABLE expertise;

-- =====================================================
-- INSERT EXPERTISE (41 records)
-- =====================================================

INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (1, 'Bác sĩ Gia Đình', '/icons/specialties/bac-si-gia-dinh.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (2, 'Tiêu Hóa Gan Mật', '/icons/specialties/tieu-hoa-gan-mat.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (3, 'Nội Tổng Quát', '/icons/specialties/noi-tong-quat.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (4, 'Nội Tiết', '/icons/specialties/noi-tiet.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (5, 'Da liễu', '/icons/specialties/da-lieu.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (6, 'Nội Tim Mạch', '/icons/specialties/noi-tim-mach.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (7, 'Nội Thần Kinh', '/icons/specialties/noi-than-kinh.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (8, 'Nội Cơ Xương Khớp', '/icons/specialties/noi-co-xuong-khop.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (9, 'Tai Mũi Họng', '/icons/specialties/tai-mui-hong.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (10, 'Mắt', '/icons/specialties/mat.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (11, 'Nội Tiêu Hoá', '/icons/specialties/noi-tieu-hoa.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (12, 'Nội Truyền Nhiễm', '/icons/specialties/noi-truyen-nhiem.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (13, 'Nội Hô Hấp', '/icons/specialties/noi-ho-hap.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (14, 'Nội Tiết Niệu', '/icons/specialties/noi-tiet-nieu.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (15, 'Ngoại Cơ Xương Khớp', '/icons/specialties/ngoai-co-xuong-khop.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (16, 'Sản - Phụ Khoa', '/icons/specialties/san-phu-khoa.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (17, 'Ngoại Tiêu Hoá', '/icons/specialties/ngoai-tieu-hoa.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (18, 'Ngoại Tiết Niệu', '/icons/specialties/ngoai-tiet-nieu.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (19, 'Tâm Lý', '/icons/specialties/tam-ly.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (20, 'Tâm Thần Kinh', '/icons/specialties/tam-than-kinh.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (21, 'Ngoại Hô Hấp', '/icons/specialties/ngoai-ho-hap.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (22, 'Ngoại Thần Kinh', '/icons/specialties/ngoai-than-kinh.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (23, 'Lồng Ngực - Mạch Máu', '/icons/specialties/long-nguc-mach-mau.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (24, 'Dinh Dưỡng', '/icons/specialties/dinh-duong.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (25, 'Thẩm mỹ da', '/icons/specialties/tham-my-da.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (26, 'Ngoại Tổng Quát', '/icons/specialties/ngoai-tong-quat.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (27, 'Dị Ứng - Miễn Dịch Lâm Sàng', '/icons/specialties/di-ung-mien-dich-lam-sang.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (28, 'Răng Hàm Mặt', '/icons/specialties/rang-ham-mat.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (29, 'Chấn Thương Chỉnh Hình', '/icons/specialties/chan-thuong-chinh-hinh.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (30, 'Vô Sinh - Hiếm Muộn', '/icons/specialties/vo-sinh-hiem-muon.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (31, 'Ngoại Ung Bướu', '/icons/specialties/ngoai-ung-buou.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (32, 'Ung Bướu', '/icons/specialties/ung-buou.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (33, 'Nam Khoa', '/icons/specialties/nam-khoa.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (34, 'Lão Khoa', '/icons/specialties/lao-khoa.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (35, 'Vật Lý Trị Liệu - Phục Hồi Chức Năng', '/icons/specialties/vat-ly-tri-lieu-phuc-hoi-chuc-nang.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (36, 'Y Học Cổ Truyền', '/icons/specialties/y-hoc-co-truyen.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (37, 'Tim Mạch Can Thiệp', '/icons/specialties/tim-mach-can-thiep.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (38, 'Tạo hình thẩm mỹ', '/icons/specialties/tao-hinh-tham-my.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (39, 'Cơ Xương Khớp - Chiropractic', '/icons/specialties/co-xuong-khop-chiropractic.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (40, 'Nha Khoa', '/icons/specialties/nha-khoa.png', '2026-06-10 18:25:35');
INSERT INTO expertise (expertise_id, expertise_name, icon_url, created_at) VALUES (41, 'Nhi Khoa', '/icons/specialties/nhi-khoa.png', '2026-06-10 18:25:35');

-- =====================================================
-- INSERT STAFF (125 records)
-- =====================================================
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (1, NULL, 1, 'BS CKII. Ngô Trung Nam', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_NAMNT.png', 0, 1, 1, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (2, NULL, 1, 'BS. Lê Tuấn', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TUANL715.png', 0, 1, 2, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (3, NULL, 1, 'BS. Nguyễn Trường Mạnh', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_MANHNT505.png', 0, 1, 3, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (4, NULL, 1, 'Bác sĩ Trần Thị Mây', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_MAYTT869.png', 0, 1, 4, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (5, NULL, 1, 'Bác sĩ Vũ Đình Khôi', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_KHOIVD039.png', 0, 1, 5, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (6, NULL, 1, 'BS.CKI. Đỗ Đăng Khoa', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_KHOADD.png', 0, 1, 6, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (7, NULL, 10, 'BS CKI. Vũ Thị Hà', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HAVUT.png', 0, 1, 7, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (8, NULL, 5, 'BS CKI. Nguyễn Thị Sen', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_SENNT816.png', 0, 1, 8, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (9, NULL, 1, 'Ths BS. Lê Hoàng Thiên', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THIENLH.png', 0, 1, 9, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (10, NULL, 1, 'BS. Đặng Quốc Bảo', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_BAODQ.png', 0, 1, 10, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (11, NULL, 1, 'BS. Hoàng Thị Anh Thư', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THUHTA.png', 0, 1, 11, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (12, NULL, 1, 'BS CKI. Nguyễn Phúc Thiện', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THIENNP410.png', 0, 1, 12, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (13, NULL, 10, 'Bác sĩ Nguyễn Thị Hường', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUONGNT195.png', 0, 1, 13, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (14, NULL, 1, 'BS. Vũ Thị Thư', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THUVT739.png', 0, 1, 14, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (15, NULL, 1, 'BS CKI. Lê Ngọc Hồng Hạnh - Bv Nhi đồng 2', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HANHLHN.png', 0, 1, 15, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (16, NULL, 1, 'TS.BS. Lê Vũ Tân - Phòng khám Nam Học và hiếm muộn Khang Trí', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TANVUL.png', 0, 1, 16, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (17, NULL, 1, 'Ths BS. Trần Thị Oanh - BV Hùng Vương', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUONGTH.png', 0, 1, 17, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (18, NULL, 1, 'Ths BS. Trịnh Xuân Quân', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-20de90c054c24de6b0c364316e394aa8.png', 0, 1, 18, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (19, NULL, 1, 'Bác sĩ Phan Thị Nga - Bv Nhi Đồng Nai', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_NGAPT462.png', 0, 1, 19, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (20, NULL, 1, 'ThS CKI BSNT. Lê Chí Hiếu', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HIEULC.png', 0, 1, 20, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (21, NULL, 1, 'Ths BS. Nguyễn Ngọc Bách - Nhi Đồng 1', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-2f3caacda3124217a9c4be86b846f19d.png', 0, 1, 21, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (22, NULL, 1, 'Bác sĩ Ca Thị Lan Nhi', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_NHICTL482.png', 0, 1, 22, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (23, NULL, 1, 'Ths BS. Nguyễn Thị Mỹ Linh', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_LINHNTM.png', 0, 1, 23, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (24, NULL, 1, 'Bác sĩ Huỳnh Công - Bệnh viện Đa khoa Quảng Nam', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_CONGH894.png', 0, 1, 24, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (25, NULL, 1, 'Ths BS. Nguyễn Đức Bảo', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_BAOND.png', 0, 1, 25, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (26, NULL, 1, 'Bác sĩ Nguyễn Quốc Duy - Nhi Khoa Sunshine', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_DUYNQ.png', 0, 1, 26, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (27, NULL, 1, 'Bác sĩ Ngô Tài Dũng - Nhi đồng 2', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_DUNGNT.png', 0, 1, 27, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (28, NULL, 1, 'BS.CKI. Phan Bá Hà', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HAPB.png', 0, 1, 28, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (29, NULL, 1, 'Ths BS. Đỗ Thanh Tân', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TANDT.png', 0, 1, 29, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (30, NULL, 1, 'TS BS. Phạm Minh Triết - Nguyên Trưởng Khoa Tâm Lý BV Nhi Đồng 1', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-f3bc60c501e4497897a6b7ced212af41.png', 0, 1, 30, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (31, NULL, 1, 'TTUT.BS.CK2 Dương Minh Trí | Phòng khám Bác sĩ Dương Minh Trí', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-pkcxkbstri_TRIDM.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (32, NULL, 1, 'Bác Sĩ Nguyễn Anh Tuấn', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS08.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (33, NULL, 1, 'Bác Sĩ Nguyễn Phi Phú', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS09.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (34, NULL, 1, 'Thạc sĩ Bác Sĩ Nguyễn Toàn Chung', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS10.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (35, NULL, 1, 'Bác Sĩ Nguyễn Tấn Phong', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS13.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (36, NULL, 1, 'Bác sĩ Cao Thị Thanh Nga', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS15.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (37, NULL, 1, 'Bác Sĩ Nguyễn Thị Thanh Vi', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS04.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (38, NULL, 1, 'Thạc sĩ Bác Sĩ Phạm Thị Lương', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS11.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (39, NULL, 1, 'Thạc sĩ Bác Sĩ Đặng Thị Niệm', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS16.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (40, NULL, 1, 'Bác sĩ CKII Bác Sĩ Nguyễn Minh Hiển', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS18.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (41, NULL, 5, 'Bác sĩ Đỗ Huy Bình', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-pkpensiliabienhoa_DHB.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (42, NULL, 1, 'Bác sĩ Nguyễn Lê Nguyên', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-4dc5ff99548b4b608f43597e86a94e95.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (43, NULL, 1, 'Ths BSNT. Đặng Nguyễn Bảo Trâm - BV Chợ Rẫy', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-94c1a2afdc23481990661d597c7e9bfa.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (44, NULL, 1, 'BS CKI Nguyễn Văn Linh', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bsgdhonganh_BS001.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (45, NULL, 1, 'BS CKI Trần Thị Mỹ Anh', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bsgdhonganh_BS002.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (46, NULL, 1, 'BS CKII Trần Thị Ngọc Lan', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bsgdhonganh_BS003.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (47, NULL, 1, 'Bác sĩ Đa khoa Đặng Bảo Trâm', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bsgdhonganh_BS004.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (48, NULL, 1, 'BS CKI. Nguyễn Thị Thanh Minh', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-cdcc8bc2ca794908ba49edf91c208430.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (49, NULL, 1, 'Bác sĩ Lê Thị Hồng Anh', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_ANHLTH.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (50, NULL, 10, 'Ths BS. Đào Thị Mỹ Châu', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_CHAUDTM.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (51, NULL, 1, 'BS CKI. Nguyễn Quốc Chương', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_CHUONGNQ.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (52, NULL, 1, 'BS CKI. Đặng Thế Cường', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_CUONGDT.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (53, NULL, 1, 'BS CKI. Trần Bá Đại - Bv Đa Khoa Đồng Nai', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_DAITB570.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (54, NULL, 1, 'BS CKI. Ngô Trần Khánh Dương', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_DUONGNTK.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (55, NULL, 1, 'Bác sĩ Nguyễn Thị Phương Duyên', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_DUYENNTP.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (56, NULL, 1, 'Bác sĩ Vũ Thị Duyên', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_DUYENVT.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (57, NULL, 1, 'Bác sĩ Võ Thị Mỷ Duyên', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_DUYENVTM.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (58, NULL, 1, 'BS CKI. Lê Đức Hải', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HAILD000.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (59, NULL, 5, 'BS CKI. Trần Thúy Hằng - Bệnh Viện 30/4', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HANGTT797.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (60, NULL, 1, 'Bác sĩ Vũ Việt Hà', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HAVV653.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (61, NULL, 1, 'Bác sĩ Trần Vũ Hoàng', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HOANGTV.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (62, NULL, 1, 'BS CKI. Nguyễn Đình Hùng  - Bệnh Viện Đa Khoa Tỉnh Gia Lai', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUNGND456.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (63, NULL, 1, 'TS BS. Nguyễn Trung Hưng - Giảng viên Đại học Y Dược Đà Nẵng', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUNGNT761.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (64, NULL, 1, 'BS. Huỳnh Thị Diễm Hương', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUONGHTD384.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (65, NULL, 1, 'BS.CKI. Lương Thu Hương - BVĐK Khu Vực Long Khánh', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUONGLT.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (66, NULL, 1, 'Bác sĩ Nguyễn Thị Hương', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUONGNT306.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (67, NULL, 1, 'Bác sĩ Mai Huy - BS tu nghiệp tại Mỹ - Nguyên BS tại BV Đại Học Y Dược', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_HUYM.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (68, NULL, 1, 'BS CKI. Nguyễn Trí Khoa -  Bệnh Viện Bình Chánh', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_KHOANT500.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (69, NULL, 1, 'Bác sĩ Đặng Xuân Khôi', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_KHOIDX212.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (70, NULL, 1, 'BS CKI. Bá Duy Khương', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_KHUONGBD.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (71, NULL, 1, 'BS CKI. Nguyễn Thị Diễm Lệ', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_LENTD.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (72, NULL, 29, 'Bác sĩ Huỳnh Duy Linh', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_LINHHD.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (73, NULL, 1, 'Bác sĩ Nguyễn Thị Thuỳ Linh - BV Ung Bứu Nghệ An', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_LINHNTT096.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (74, NULL, 1, 'Bác sĩ Phạm Thị Khánh Linh', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_LINHPK791.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (75, NULL, 1, 'Ths BS. Dương Bửu Lộc', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_LOCDB.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (76, NULL, 1, 'BS CKI. Trần Bình Long - Bệnh Viện An Bình', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_LONGTB538.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (77, NULL, 1, 'Bác sĩ Vũ Hải My', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_MYVH.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (78, NULL, 1, 'BS CKI. Lữ Hồng Nam', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_NAMLH.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (79, NULL, 1, 'Bác sĩ Đinh Thị Thúy Nguyên', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_NGUYENDTT.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (80, NULL, 1, 'THS BS. Trương Gia Phúc - Bệnh Viện Quân Y 7A', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_PHUCTG569.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (81, NULL, 1, 'Bác sĩ Trần Vĩnh Phúc', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_PHUCTV.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (82, NULL, 1, 'Ths BSNT. Vũ Đức Quân', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_QUANVD.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (83, NULL, 1, 'ThS CKI BSNT. Trần Minh Sang', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_SANGTM605.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (84, NULL, 1, 'BS CKI. Dương Thành Sơn Phòng Khám Thiện Mỹ Sài Gòn', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_SONDT115.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (85, NULL, 1, 'Bác sĩ Tạ Thanh Sơn', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_SONTT.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (86, NULL, 1, 'Ths BS. Trần Minh Tân - BV Nhi Đồng Thành Phố', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TANTM.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (87, NULL, 29, 'THS BS. Đoàn Minh Thái', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THAIDM.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (88, NULL, 10, 'BS CKI. Nguyễn Thị Thanh Thảo', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THAONGTT2.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (89, NULL, 1, 'Bác sĩ Châu Minh Thoại', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THOAICM.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (90, NULL, 1, 'Bác sĩ Nguyễn Thị Diệu Thúy - Bệnh Viện Lê Văn Việt', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_THUYNTD850.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (91, NULL, 1, 'Bác sĩ Trần Thị Tin - BVĐK Khu Vực Long Thành', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TINTT904.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (92, NULL, 1, 'Bác sĩ Nguyễn Hữu Toàn', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TOANNH.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (93, NULL, 1, 'BS CKI. Ngô Trần Hoàng Trí', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TRINTH.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (94, NULL, 1, 'Bác sĩ Nguyễn Hữu Trung - BV Thành Phố Thủ Đức', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TRUNGNH990.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (95, NULL, 1, 'Bệnh viện Đa khoa Singapore', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_TVVSGH.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (96, NULL, 5, 'Bác sĩ Phạm Thanh Uyên', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_UYENPT.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (97, NULL, 5, 'BS CKI. Đoàn Thị Bích Vân', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_VANDTB921.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (98, NULL, 1, 'BS CKII. Nguyễn Thị Thùy Vân - Bệnh Viện Nhi Đồng 1', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_VANNTT190.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (99, NULL, 1, 'BS CKI. Nguyễn Thị Diệu Vy', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_VYND067.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (100, NULL, 1, 'Bác sĩ Nguyễn Thị Bảo Yến', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-digimed_YENNTB.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (101, NULL, 1, 'Bác sĩ CKI Dư Phương Thụy Vy', 'Nữ', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS05.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (102, NULL, 1, 'Bác sĩ CKI Phú Quốc An', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS06.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (103, NULL, 1, 'Bác sĩ CKI Vi Văn Cường', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS07.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (104, NULL, 1, 'Bác sĩ CKII Trần Thanh Long', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS12.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (105, NULL, 1, 'Bác sĩ CKI Nguyễn Văn Hoàng', 'Nam', NULL, NULL, NULL, 'DOCTOR', '5 năm', '/images/doctors/doctor-bvgangwhoo_BS14.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (106, NULL, 15, 'Nguyễn Minh Khoa', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '3 năm', '/images/lab-techs/lab-1.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (107, NULL, 15, 'Trần Thị Hương', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '4 năm', '/images/lab-techs/lab-2.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (108, NULL, 15, 'Lê Quốc Bảo', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '5 năm', '/images/lab-techs/lab-3.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (109, NULL, 15, 'Phạm Thanh Tâm', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '6 năm', '/images/lab-techs/lab-4.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (110, NULL, 15, 'Nguyễn Ngọc Mai', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '7 năm', '/images/lab-techs/lab-5.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (111, NULL, 15, 'Đỗ Thành Đạt', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '8 năm', '/images/lab-techs/lab-6.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (112, NULL, 15, 'Võ Minh Khôi', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '9 năm', '/images/lab-techs/lab-7.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (113, NULL, 15, 'Bùi Thanh Hà', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '10 năm', '/images/lab-techs/lab-8.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (114, NULL, 15, 'Nguyễn Thanh Bình', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '3 năm', '/images/lab-techs/lab-9.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (115, NULL, 15, 'Trần Quốc Dũng', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '4 năm', '/images/lab-techs/lab-10.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (116, NULL, 15, 'Lê Mỹ Linh', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '5 năm', '/images/lab-techs/lab-11.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (117, NULL, 15, 'Hoàng Anh Tú', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '6 năm', '/images/lab-techs/lab-12.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (118, NULL, 15, 'Phan Thị Hạnh', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '7 năm', '/images/lab-techs/lab-13.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (119, NULL, 15, 'Vũ Khánh Ly', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '8 năm', '/images/lab-techs/lab-14.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (120, NULL, 15, 'Đặng Nhật Minh', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '9 năm', '/images/lab-techs/lab-15.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (121, NULL, 15, 'Nguyễn Gia Huy', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '10 năm', '/images/lab-techs/lab-16.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (122, NULL, 15, 'Lê Thanh Tùng', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '3 năm', '/images/lab-techs/lab-17.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (123, NULL, 15, 'Võ Khánh Vy', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '4 năm', '/images/lab-techs/lab-18.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (124, NULL, 15, 'Phạm Quỳnh Anh', 'Nam', NULL, NULL, NULL, 'LAB_TECH', '5 năm', '/images/lab-techs/lab-19.jpg', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO staff (staff_id, account_id, expertise_id, full_name, gender, date_of_birth, phone, address, staff_type, experience, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (125, NULL, 15, 'Trần Minh Đức', 'Nữ', NULL, NULL, NULL, 'LAB_TECH', '6 năm', '/images/lab-techs/lab-20.jpg', 0, 0, 0, '2026-06-10 18:25:35');

-- =====================================================
-- INSERT SERVICE (69 records)
-- =====================================================
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (1, 'Gói Xét Nghiệm Sinh Hóa Cơ Bản Tại Nhà', 'LAB_TEST', 1015000, '0', '/images/services/home/home-pkg-c09a907bb4fb4123913d67fd71b13bd1.jpg', 0, 1, 1, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (2, 'Gói xét nghiệm sức khỏe sinh sản nữ - nâng cao (6 test)', 'LAB_TEST', 1338000, '0', '/images/services/home/home-pkg-diag005_DV008.jpg', 0, 1, 2, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (3, 'Gói XN Viêm gan - cơ bản (3 test)', 'LAB_TEST', 420000, '0', '/images/services/home/home-pkg-diag005_DV011.jpg', 0, 1, 3, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (4, 'Gói XN đái tháo đường - cơ bản (3 test)', 'LAB_TEST', 159000, '0', '/images/services/home/home-pkg-diag005_DV013.jpg', 0, 1, 4, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (5, 'Gói xét nghiệm máu cơ bản - Nam/Nữ', 'LAB_TEST', 2110000, '0', '/images/services/home/home-pkg-pkvietuc_GK007.jpg', 0, 1, 5, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (6, 'Gói XN Viêm gan - nâng cao (6 test)', 'LAB_TEST', 1117000, '0', '/images/services/home/home-pkg-diag005_DV012.jpg', 0, 1, 6, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (7, 'Gói Tầm soát ung thư gan', 'LAB_TEST', 2697000, '0', '/images/services/list/list-pkg-pkdymsg_GK12.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (8, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nam)', 'LAB_TEST', 4410000, '0', '/images/services/list/list-pkg-pkdymsg_GK21.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (9, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nữ có gia đình)', 'LAB_TEST', 5080000, '0', '/images/services/list/list-pkg-pkdymsg_GK23.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (10, 'Khám sức khỏe tổng quát tiêu chuẩn (Nam)', 'LAB_TEST', 1850000, '0', '/images/services/list/list-pkg-pkdymsg_GK28.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (11, 'Khám sức khỏe tổng quát toàn diện (Nữ)', 'LAB_TEST', 2890000, '0', '/images/services/list/list-pkg-pkdymsg_GK32.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (12, 'Gói Xét Nghiệm Tổng Quát', 'LAB_TEST', 2300000, '0', '/images/services/list/list-pkg-pkdkvigor_B1.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (13, 'Gói Xét Nghiệm Tầm Soát Ung Thư ở Nữ Giới', 'LAB_TEST', 1930000, '0', '/images/services/list/list-pkg-pkdkvigor_B3.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (14, 'Tầm soát ung thư dạ dày', 'LAB_TEST', 3100000, '0', '/images/services/list/list-pkg-drcheck_014.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (15, 'Tầm soát ung thư đại tràng', 'LAB_TEST', 4440000, '0', '/images/services/list/list-pkg-drcheck_008.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (16, 'Tầm soát chức năng phổi và ung thư phổi', 'LAB_TEST', 1825000, '0', '/images/services/list/list-pkg-pkdymsg_GK15.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (17, 'Khám sức khỏe tổng quát tiêu chuẩn (Nam)', 'LAB_TEST', 1850000, '0', '/images/services/list/list-pkg-pkdymhn_GK28.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (18, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nam)', 'LAB_TEST', 4410000, '0', '/images/services/list/list-pkg-pkdymhn_GK21.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (19, 'Gói Tầm soát vòm họng', 'LAB_TEST', 1100000, '0', '/images/services/list/list-pkg-pkdymhn_GK20.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (20, 'Gói Tầm soát ung thư gan', 'LAB_TEST', 2697000, '0', '/images/services/list/list-pkg-pkdymhn_GK12.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (21, 'Khám sức khỏe tổng quát toàn diện (Nữ có gia đình)', 'LAB_TEST', 3040000, '0', '/images/services/list/list-pkg-pkdymhn_GK33.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (22, 'Tầm soát đột quỵ', 'LAB_TEST', 4445000, '0', '/images/services/list/list-pkg-pkdymhn_GK16.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (23, 'Tầm soát chức năng phổi và ung thư phổi', 'LAB_TEST', 1825000, '0', '/images/services/list/list-pkg-pkdymhn_GK15.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (24, 'Tầm soát ung thư cổ tử cung (Nữ Giới)', 'LAB_TEST', 1826000, '0', '/images/services/list/list-pkg-pkdymhn_GK18.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (25, 'Tầm soát ung thư buồng trứng (Nữ Giới)', 'LAB_TEST', 1350000, '0', '/images/services/list/list-pkg-pkdymhn_GK17.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (26, 'Tầm soát ung thư tuyến vú (Nữ Giới)', 'LAB_TEST', 1870000, '0', '/images/services/list/list-pkg-pkdymhn_GK19.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (27, 'Tầm soát chức năng tuyến giáp, ung thư tuyến giáp', 'LAB_TEST', 1300000, '0', '/images/services/list/list-pkg-pkdymhn_GK14.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (28, 'Tầm soát ung thư tuyến tuyền liệt (Nam Giới)', 'LAB_TEST', 1310000, '0', '/images/services/list/list-pkg-pkdymhn_GK13.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (29, 'Khám sức khỏe tổng quát cơ bản (Nữ)', 'LAB_TEST', 1670000, '0', '/images/services/list/list-pkg-pkdymhn_GK25.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (30, 'Khám sức khỏe tổng quát cơ bản (Nữ có gia đình)', 'LAB_TEST', 1820000, '0', '/images/services/list/list-pkg-pkdymhn_GK26.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (31, 'Khám sức khỏe tổng quát tiêu chuẩn (Nữ)', 'LAB_TEST', 2150000, '0', '/images/services/list/list-pkg-pkdymhn_GK29.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (32, 'Khám sức khỏe tổng quát cơ bản (Nam)', 'LAB_TEST', 1590000, '0', '/images/services/list/list-pkg-pkdymhn_GK24.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (33, 'Khám sức khỏe tổng quát tiêu chuẩn (Nữ có gia đình)', 'LAB_TEST', 2300000, '0', '/images/services/list/list-pkg-pkdymhn_GK30.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (34, 'Khám sức khỏe tổng quát toàn diện (Nữ)', 'LAB_TEST', 2890000, '0', '/images/services/list/list-pkg-pkdymhn_GK32.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (35, 'Khám sức khỏe tổng quát toàn diện (Nam)', 'LAB_TEST', 2590000, '0', '/images/services/list/list-pkg-pkdymhn_GK31.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (36, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nữ có gia đình)', 'LAB_TEST', 5080000, '0', '/images/services/list/list-pkg-pkdymhn_GK23.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (37, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nữ độc thân)', 'LAB_TEST', 4930000, '0', '/images/services/list/list-pkg-pkdymhn_GK22.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (38, 'Gói khám tổng quát toàn diện cho khách hàng trên 40 tuổi Nam', 'LAB_TEST', 2950000, '0', '/images/services/list/list-pkg-pkhangxanh_DV007.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (39, 'Gói khám tổng quát nâng cao cho khách hàng dưới 30 tuổi', 'LAB_TEST', 1550000, '0', '/images/services/list/list-pkg-pkhangxanh_DV002.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (40, 'Gói khám tổng quát cơ bản', 'LAB_TEST', 1050000, '0', '/images/services/list/list-pkg-pkhangxanh_DV001.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (41, 'Gói khám tổng quát nâng cao cho khách hàng từ 30 đến 50 tuổi Nữ', 'LAB_TEST', 1700000, '0', '/images/services/list/list-pkg-pkhangxanh_DV004.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (42, 'Gói khám tổng quát nâng cao cho khách hàng từ 30 đến 50 tuổi Nam', 'LAB_TEST', 1600000, '0', '/images/services/list/list-pkg-pkhangxanh_DV003.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (43, 'Gói khám tổng quát toàn diện cho khách hàng trên 40 tuổi Nữ (sử dụng Pathtezt)', 'LAB_TEST', 4300000, '0', '/images/services/list/list-pkg-pkhangxanh_DV009.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (44, 'Gói khám tổng quát nâng cao cho khách hàng trên 50 tuổi Nữ', 'LAB_TEST', 2000000, '0', '/images/services/list/list-pkg-pkhangxanh_DV006.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (45, 'Gói khám tổng quát nâng cao cho khách hàng trên 50 tuổi Nam', 'LAB_TEST', 2000000, '0', '/images/services/list/list-pkg-pkhangxanh_DV005.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (46, 'Gói khám tổng quát toàn diện cho khách hàng trên 40 tuổi Nữ (sử dụng Pap''s)', 'LAB_TEST', 3900000, '0', '/images/services/list/list-pkg-pkhangxanh_DV008.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (47, 'Khám sức khỏe tổng quát toàn diện (Nam)', 'LAB_TEST', 2590000, '0', '/images/services/list/list-pkg-pkdympmh_GK31.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (48, 'Khám sức khỏe tổng quát tiêu chuẩn (Nữ có gia đình)', 'LAB_TEST', 2300000, '0', '/images/services/list/list-pkg-pkdympmh_GK30.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (49, 'Khám sức khỏe tổng quát toàn diện (Nữ có gia đình)', 'LAB_TEST', 3040000, '0', '/images/services/list/list-pkg-pkdympmh_GK33.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (50, 'Khám sức khỏe tổng quát toàn diện (Nữ)', 'LAB_TEST', 2890000, '0', '/images/services/list/list-pkg-pkdympmh_GK32.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (51, 'Tầm soát ung thư tuyến tuyền liệt (Nam Giới)', 'LAB_TEST', 1310000, '0', '/images/services/list/list-pkg-pkdympmh_GK13.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (52, 'Tầm soát ung thư buồng trứng (Nữ Giới)', 'LAB_TEST', 1350000, '0', '/images/services/list/list-pkg-pkdympmh_GK17.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (53, 'Tầm soát đột quỵ', 'LAB_TEST', 4445000, '0', '/images/services/list/list-pkg-pkdympmh_GK16.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (54, 'Tầm soát ung thư tuyến vú (Nữ Giới)', 'LAB_TEST', 1870000, '0', '/images/services/list/list-pkg-pkdympmh_GK19.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (55, 'Tầm soát ung thư cổ tử cung (Nữ Giới)', 'LAB_TEST', 1826000, '0', '/images/services/list/list-pkg-pkdympmh_GK18.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (56, 'Gói Tầm soát ung thư gan', 'LAB_TEST', 2697000, '0', '/images/services/list/list-pkg-pkdympmh_GK12.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (57, 'Tầm soát chức năng phổi và ung thư phổi', 'LAB_TEST', 1825000, '0', '/images/services/list/list-pkg-pkdympmh_GK15.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (58, 'Tầm soát chức năng tuyến giáp, ung thư tuyến giáp', 'LAB_TEST', 1300000, '0', '/images/services/list/list-pkg-pkdympmh_GK14.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (59, 'Khám sức khỏe tổng quát cơ bản (Nữ có gia đình)', 'LAB_TEST', 1820000, '0', '/images/services/list/list-pkg-pkdympmh_GK26.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (60, 'Khám sức khỏe tổng quát cơ bản (Nữ)', 'LAB_TEST', 1670000, '0', '/images/services/list/list-pkg-pkdympmh_GK25.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (61, 'Khám sức khỏe tổng quát tiêu chuẩn (Nam)', 'LAB_TEST', 1850000, '0', '/images/services/list/list-pkg-pkdympmh_GK28.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (62, 'Khám sức khỏe tổng quát tiêu chuẩn (Nữ)', 'LAB_TEST', 2150000, '0', '/images/services/list/list-pkg-pkdympmh_GK29.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (63, 'Gói Tầm soát vòm họng', 'LAB_TEST', 1100000, '0', '/images/services/list/list-pkg-pkdympmh_GK20.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (64, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nữ độc thân)', 'LAB_TEST', 4930000, '0', '/images/services/list/list-pkg-pkdympmh_GK22.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (65, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nam)', 'LAB_TEST', 4410000, '0', '/images/services/list/list-pkg-pkdympmh_GK21.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (66, 'Khám sức khỏe tổng quát cơ bản (Nam)', 'LAB_TEST', 1590000, '0', '/images/services/list/list-pkg-pkdympmh_GK24.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (67, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nữ có gia đình)', 'LAB_TEST', 5080000, '0', '/images/services/list/list-pkg-pkdympmh_GK23.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (68, 'Tầm soát ung thư buồng trứng (Nữ Giới)', 'LAB_TEST', 1350000, '0', '/images/services/list/list-pkg-pkdymsg_GK17.png', 0, 0, 0, '2026-06-10 18:25:35');
INSERT INTO service (service_id, service_name, service_type, original_price, discount_price, image_url, is_deleted, is_featured, featured_priority, created_at) VALUES (69, 'Khám sức khỏe tổng quát (cho người cao tuổi) (Nữ độc thân)', 'LAB_TEST', 4930000, '0', '/images/services/list/list-pkg-pkdymsg_GK22.png', 0, 0, 0, '2026-06-10 18:25:35');

SET FOREIGN_KEY_CHECKS = 1;

-- =====================================================
-- VERIFY
-- =====================================================
SELECT '✅ Expertise' as status, COUNT(*) as total FROM expertise
UNION ALL
SELECT '✅ Staff', COUNT(*) FROM staff
UNION ALL
SELECT '✅ Service', COUNT(*) FROM service;
